// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sendgrid.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import sendgrid.implementation.ConfigurationMapper;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class HandleEvent extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __Parameter;
	private sendgrid.proxies.Event Parameter;

	public HandleEvent(IContext context, IMendixObject Parameter)
	{
		super(context);
		this.__Parameter = Parameter;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.Parameter = __Parameter == null ? null : sendgrid.proxies.Event.initialize(getContext(), __Parameter);

		// BEGIN USER CODE
		ConfigurationMapper.getInstance().processEvent(getContext(), Parameter)	;
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "HandleEvent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
