// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sendgrid.actions;

import java.security.interfaces.ECPublicKey;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import sendgrid.implementation.EventWebhook;

public class VerifySendgridSignature extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String publicKey;
	private java.lang.String payload;
	private java.lang.String signature;
	private java.lang.String timestamp;

	public VerifySendgridSignature(IContext context, java.lang.String publicKey, java.lang.String payload, java.lang.String signature, java.lang.String timestamp)
	{
		super(context);
		this.publicKey = publicKey;
		this.payload = payload;
		this.signature = signature;
		this.timestamp = timestamp;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		EventWebhook eventWebhook = new EventWebhook();
		
		ECPublicKey ecpk = eventWebhook.ConvertPublicKeyToECDSA(publicKey);
		return eventWebhook.VerifySignature(ecpk, payload, signature, timestamp);
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "VerifySendgridSignature";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
